### ISSUE TITLE
Ability to clear out requests

### ISSUE THREAD

**Issue by brandondoran** [kubeshark/kubeshark#1223]
A feature I find wishing for is the ability to clear out requests currently displayed in the UI. The use case is when you're troubleshooting requests between services and because requests just keep stacking up it's easy to get lost and lose track of what's what. I would be nice to reset and have a clear slate between your tests. This would be similar to whole web browser dev tools, network tab allows you to clear out requests.

**Comment by alongir** [comment]
Brandon, thanks for opening this topic. I assume you tried the following options and they were less helpful:
1. Refresh the entire Mizu page, which is less clean but still resets the page
2. Use the pause button (or scroll up which does the same)
In any event, if I read correctly, you recommend adding a "reset" button, similar to what you'd have in Chrome Dev Tools that basically erases the existing requests from the screen. Please correct me if I didn't get that right. 
We are preparing the list of next additional features to add to Mizu, so please feel free to open up additional topic/feature request.

**Comment by brandondoran** [comment]
Hi @alongir

1. I've tried doing a hard refresh on the page but the old requests are re-populated. I have been ctrl-c'ing in the terminal where I `mizu tap` and then re-`tap`ping to clear out the requests. This gets annoying because I usually have filters to exclude health checks, redis requests, etc. I have to remember to copy and paste my filters back.
2. pause doesn't really accomplish what I want either.

Yes, a "reset" or "clear" button would be exactly what i'm looking for. Just a way to start over and clear out the history so as to be able start over fresh. 

The button in Chrome dev tools network tab:

<img width="452" alt="Screen Shot 2022-10-31 at 8 37 32 AM" src="https://user-images.githubusercontent.com/1189930/199048868-c3b243e4-4cad-4861-b68c-437b32626fc3.png">

**Comment by alongir** [comment]
Thanks @brandondoran! We'll make sure this goes into one of the next releases. 
Appreciate you taking the time and helping us improve Mizu.

**Comment by mertyildiran** [comment]
@brandondoran with [the latest stable release (38.1)](https://github.com/kubeshark/kubeshark/releases/tag/38.1):

Kubeshark sets/gets the filter from the `q` query parameter. If you add `and timestamp >= now()` to your filter then you will always have a fresh start of stream in the left-pane.
