### ISSUE TITLE
Why don't view GUI in internet? we only open GUI in localhost?

### ISSUE THREAD

**Issue by QWQyyy** [kubeshark/kubeshark#1244]
We deploy K8s in cloud compute cluster, and deploy kubeshark, it working my server but can't view it in internet IP, it only runing private IP.
So, I hope colud give ours some public IP study paper.

**Comment by mertyildiran** [comment]
I guess https://github.com/kubeshark/kubeshark/issues/1243#issuecomment-1325657582 is answering this question as well.

**Comment by alongir** [comment]
Out of the box, kubeshark-api-server service is created with the type ClusterIP to ensure it is not accessible outside of the cluster. At any time after running the `kubeshark` CLI, you can create an ingress service with a public IP to pointing to "kubeshark-api-server" service (e.g. [port forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)).

**Comment by QWQyyy** [comment]
well notes, thank you

**Comment by QWQyyy** [comment]
> Out of the box, kubeshark-api-server service is created with the type ClusterIP to ensure it is not accessible outside of the cluster. At any time after running the `kubeshark` CLI, you can create an ingress service with a public IP to pointing to "kubeshark-api-server" service (e.g. [port forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)).

OK, I find a nice way to address it, we noly edit kubeshark-api-server svc, and apply it
`kubectl edit -n kubeshark svc kubeshark-api-server`
`apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-27T07:37:32Z"
  labels:
    app.kubernetes.io/created-by: kubeshark-cli
    app.kubernetes.io/managed-by: kubeshark
  name: kubeshark-api-server
  namespace: kubeshark
  resourceVersion: "11119"
  uid: 40b7a925-c3c3-4db3-84bb-aadcc925af30
spec:
  clusterIP: 10.96.77.239
  clusterIPs:
  - 10.96.77.239
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    nodePort: 31113
    port: 80
    protocol: TCP
    targetPort: 8899
  selector:
    app: kubeshark-api-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}`

we can open GUI in internet
![image](https://user-images.githubusercontent.com/54056797/204127515-36c0cf41-8616-49f6-8bb0-43aa711ba75e.png)

cool!
![image](https://user-images.githubusercontent.com/54056797/204127555-b99a7dff-203a-467b-adb2-35e0c5ca04f9.png)

thank you!

**Comment by tboevil** [comment]
Modify the proxy-host in ~/.kubeshark/config.yaml to be accessible from the outside

**Comment by alongir** [comment]
For V38+, take a look here: https://docs.kubeshark.co/en/config#web-ui-ip-and-accessibility
Let us know if that doesn't work for you.
