### ISSUE TITLE
Intranet k8s

### ISSUE THREAD

**Issue by YueChuang** [kubeshark/kubeshark#1254]
My K8S is an intranet. I tried to download the Docker image required by Kubeshark in advance, and then run Kubeshark. But I found in the log that it still pulls the image from the network. Is there a solution?

**Comment by jbertozzi** [comment]
Looking at the source code you can find some references to the helm chart, so I guess the following should work for the backend:

```
helm repo add mizu https://static.up9.com/mizu/helm
helm show values mizu/up9mizu
helm template mizu/up9mizu --set container.baseRepo=toto.com
```

For the hub, I am not able to find how to change the image pulled by the `kubeshark tap` command.

Displaying the default config with `kubeshark config` did not help.

Maybe installing the backend via the helm chart, and the then editing the hub pod yaml will do the trick.

Too bad this is not documented, the project looks awesome.

**Comment by alongir** [comment]
@jbertozzi can you read this thread and see if this is a duplicate: https://github.com/kubeshark/kubeshark/issues/1256
Thanks!

**Comment by alongir** [comment]
Starting V38+, please take a look here: https://docs.kubeshark.co/en/config#private-docker-registry
Let us know if that doesn't work.

**Comment by jbertozzi** [comment]
Everything works as expected using a private registry, thank you!
