### ISSUE TITLE
How to set Hub (formerly agent) image/registry?

### ISSUE THREAD

**Issue by mdaslamansari** [kubeshark/kubeshark#1256]
### Is your feature request related to a problem? Please describe.

We have not whitelisted docker hub in our environment. All the images that we need we import them from DockerHub to our private ACR. Is there any way to configure kubeshark to pull image from private ACR?

We are getting below error -

E1129 12:17:27.638349   23008 proxy_server.go:147] Error while proxying request: context canceled

### Describe the solution you'd like to see

Configuration to set image pull location.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@mdaslamansari regarding the latest stable release `37.0`; There is an option to set the Docker image: `--set agent-image=<YOUR_IMAGE>`

So, what you need to do is;

```shell
docker pull kubeshark/kubeshark:37.0
docker image tag kubeshark/kubeshark:37.0 gcr.io/example/example:latest
docker push gcr.io/example/example:latest
kubeshark tap -A --set agent-image=gcr.io/example/example:latest
```

**Comment by mdaslamansari** [comment]
@mertyildiran Thanks a lot and with it I can see it is pulling image from my private ACR.

I can see it has created kubeshark pods and daemonSet as well...

But, with kubeshark tap command I am seeing error as - E1130 14:16:14.811355    5240 proxy_server.go:147] Error while proxying request: context canceled

Its web page is coming up but saying Tapping 0 pods in namespaces....

I am using Private AKS behind the firewall and trying to use this tool in it.

**Comment by mdaslamansari** [comment]
@mertyildiran @matlockx - Please help

**Comment by satrox28** [comment]
Hi @mertyildiran 

I am trying to do the same. I have pushed the image to private registry, now when I run the tap command it's unable to pull the image as it need credentials to access the registry, how can I provide the image pull secret?.

**Comment by mertyildiran** [comment]
@mdaslamansari Kubeshark establishes a proxy to allow you to see the UI. I think the proxy creation is failed. It uses [`kubectl proxy`](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#directly-accessing-the-rest-api) for that. Does `kubectl proxy` for you?

**Comment by mdaslamansari** [comment]
kubectl proxy is working for me but not the actual command... also, not getting any data on UI...

**Comment by gadotroee** [comment]
Hi @mdaslamansari , 

Actually as we can see [here ](https://github.com/kubeshark/kubeshark/blob/master/cmd/common.go#L25-L50) we are trying to create proxy in two ways, first (similar to 'kubectl proxy') and then if it fails we are trying to create port forwarding to the pod.

Do you this message (context canceled) immediately or it takes time until it is canceled? (if it takes time you can try to create proxy/port-forward manually and see if you can access the UI but I don't want to jump to propose anything before I know it really takes time)

In both cases it will be helpful to get logs from your execution, it might help understand where is the failure comes from

**Comment by satrox28** [comment]
> @satrox28 I think you need a way to set `imagePullSecrets` like it's described in [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret). Is that right? If so then there is no such option but we can add it in the following releases.

Yes, right.

May I know the ETA. I am unable to use this tool until then, thanks.

**Comment by mertyildiran** [comment]
With [the latest stable release (38.1)](https://github.com/kubeshark/kubeshark/releases/tag/38.1):

Pull the 3 images of Kubeshark:
```
docker pull docker.io/kubeshark/hub:latest
docker pull docker.io/kubeshark/hub:latest
```

**Comment by alongir** [comment]
Starting V38+, please take a look here: https://docs.kubeshark.co/en/config#private-docker-registry
