### ISSUE TITLE
Opt out of version checking

### ISSUE THREAD

**Issue by FollieHiyuki** [kubeshark/kubeshark#1257]
**Describe the bug**
I'm trying to package `kubeshark` for my Linux distro. As the package is maintained by me and I have another channel to track the release (e.g. Github notifications), I find version checking a bit annoying. It also slows down the command (to call Github API) every time it is invoked.

**Expected behavior**
Having a method (e.g. config option, specific environment variable) to opt out of this behavior. An environment variable is a better option here I think, maybe something like `$KUBESHARK_DISABLE_VERSION_CHECK`.

**Comment by mertyildiran** [comment]
@FollieHiyuki that's a valid point. Would you like to prefer an environment variable `$KUBESHARK_DISABLE_VERSION_CHECK` or a CLI argument `--disable-version-check`?

**Comment by FollieHiyuki** [comment]
I'd prefer an environment variable. It's more convenient, and more persistent in my opinion.

Thanks for considering it.

**Comment by mertyildiran** [comment]
@FollieHiyuki `KUBESHARK_DISABLE_VERSION_CHECK` environment variable is added with [the latest stable release (38.1)](https://github.com/kubeshark/kubeshark/releases/tag/38.1).
