### ISSUE TITLE
[Feature Request:] Deploy to remote server

### ISSUE THREAD

**Issue by clcc2019** [kubeshark/kubeshark#1259]
### Contact Details

dsong.cc@gmail.com

### Is your feature request related to a problem? Please describe.

Deploy to remote server,The instance does not have a public network, and port mapping cannot be used. I hope to use ingress to access

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
@clcc2019 can you read this thread and let me know if you think this is a duplicate: https://github.com/kubeshark/kubeshark/issues/1244
Thanks!
