### ISSUE TITLE
Hub

### ISSUE THREAD

**Issue by Jamiejayz13** [kubeshark/kubeshark#1271]
**Describe the bug**

**To Reproduce**
1. Run `kubeshark <command> ...`
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Logs**
Upload logs:
1. Run the kubeshark command with `--set dump-logs=true` (e.g `kubeshark tap --set dump-logs=true`)
2. Try to reproduce the issue
3. <kbd>CTRL</kbd>+<kbd>C</kbd> on terminal tab which runs `kubeshark`
4. Upload the logs zip file from `~/.kubeshark/kubeshark_logs_**.zip`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Web Browser: [e.g. Google Chrome]

**Additional context**

**Comment by mertyildiran** [comment]
Closing since the issue description is [the bug report template](https://github.com/kubeshark/kubeshark/blob/8b9b3c2fc2db0634188a44f91554d2d087337d03/.github/ISSUE_TEMPLATE/bug_report.md).
