### ISSUE TITLE
[Feature Request:] Make Kubeshark accessible from a public IP

### ISSUE THREAD

**Issue by vilayilarun** [kubeshark/kubeshark#1278]
### Contact Details

vilayilarun@gmail.com

### Is your feature request related to a problem? Please describe.

How this can be run on the host IP, not on localhost

### Describe the solution you'd like to see

The dashboard IP is tied to the localhost 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vilayilarun** [comment]
The kubeshark is currently tied to the localhost and required additional Nginx configurations for exposing the ports

**Comment by vilayilarun** [comment]
That's Great, Thank you

**Comment by alongir** [comment]
@vilayilarun please take a look here: https://docs.kubeshark.co/en/config#web-ui-ip-and-accessibility
Let us know if that doesn't work for you.

**Comment by vilayilarun** [comment]
Wow. Great, it's working.
