### ISSUE TITLE
Kubeshark fails to install inside docker

### ISSUE THREAD

**Issue by peter-dolkens** [kubeshark/kubeshark#1281]
**Describe the bug**
Kubeshark is able to be installed on Apple Silicon, however fails to install when installing into a docker container.

**To Reproduce**
1. Step into an ubuntu 20 command line inside docker on Apple Silicon
2. Run `yes | sh <(curl -Ls https://kubeshark.co/install)`
3. See error

**Expected behavior**
Kubeshark installs on Apple Silicon, and I suspect will run inside the image too - but validation is currently preventing it from trying

**Logs**
Upload logs:

```
➜  /app git:(managed) ✗ yes | sh <(curl -Ls https://kubeshark.co/install)

🛑 Unsupported OS "linux" or architecture "aarch64". Failed to install Kubeshark.
Please report 🐛 to https://github.com/kubeshark/kubeshark/issues
➜  /app git:(managed) ✗ uname -a
Linux 60dedc527710 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Desktop (please complete the following information):**
 - OS: macOS + Ubuntu 20

**Comment by mertyildiran** [comment]
@peter-dolkens thanks for reporting it. We have fixed the install script. Please try it again.

**Comment by mertyildiran** [comment]
Closing, assuming it's fixed.

**Comment by peter-dolkens** [comment]
Sorry - was away for the Christmas break - I can confirm this appears to be working now!

Thanks for a quick turn around!
