### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by aantn** [kubeshark/kubeshark#1282]
![Screen Shot 2022-12-25 at 15 01 59](https://user-images.githubusercontent.com/494087/209468928-6c74eb5c-9962-4cda-b183-9401a3e25481.png)

This happens when the maximum number of people have used the invite. You need to generate a new link.

**Comment by alongir** [comment]
Thanks @aantn ! Fixed with this: https://github.com/kubeshark/landing/commit/dbbf6b72b6c69fd998c5910f4d68bea77cc652b4
