### ISSUE TITLE
Requesting for a way to patch the objects created by kubeshark.

### ISSUE THREAD

**Issue by rajeeshckr** [kubeshark/kubeshark#1284]
### Contact Details

rajeesh.ckr@gmail.com

### Is your feature request related to a problem? Please describe.

We have OPA rules which block running kubeshark components in the cluster. For instance, admission webhook was rejecting the request for the following reasons.

- kubeshark-api-server basenine: should have a livenessProbe since it has a readinessProbe. If you are sure this container does not need a livenessProbe
- kubeshark-api-server container basenine: Set Pod spec.securityContext.runAsNonRoot=true to improve your projects and the clusters security.
- kubeshark-api-server: is using disallowed toleration {"effect": "NoExecute", "operator": "Exists"}.
- kubeshark-api-server: you must provide labels {"product", "project", "team"}.

Can we think of a way to overcome this? Some options which I can think of are listed below.

### Option 1:
Pass an overriding patch yaml for the pod/service/ns objects getting created for kubeshark hub resources through command line. User can pass a patch along with the `tap` command to adjust the job/pod/ns objects before being submitted to API server.

### Option 2:
Pass additional labels for pod/service/ns as a command line option. In that case, we can provide this label `opa-gatekeeper-disabled:true` which will disable opa validation for the objects. This seems like an easy approach to implement.

Hope other teams also can get benefitted from this change.

Thanks a lot!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mateuszdrab** [comment]
Similar situation in my issue https://github.com/kubeshark/kubeshark/issues/1318
I think the best way to handle this would be to add `--labels` and `--tolerations` (and possibly `--annotations`) flags

Currently worked around this by exporting my own set of manifests and deploying them on demand, then running kubeshark tap and proxy which reuses my pods.

**Comment by mertyildiran** [comment]
We have published a Helm chart which can be found in [here](https://github.com/kubeshark/kubeshark/tree/master/helm-chart). It has [these options](https://github.com/kubeshark/kubeshark/blob/master/helm-chart/values.yaml#L43-L45) to set the labels, tolerations and node selector in the `values.yaml`.
