### ISSUE TITLE
[Feature Request:] Set independent container image versions for all components

### ISSUE THREAD

**Issue by alen-z** [kubeshark/kubeshark#1293]
### Is your feature request related to a problem? Please describe.

Problem is our cluster has a policy not to allow `latest` tags. Setting `tap.docker.tag: 37.0` produces and error since it tries to apply this tag to all components:
```
2023-01-09T12:57:02+01:00 ERR tapRunner.go:404 > Watching events. event=kubeshark-hub.1738a2095077dd7f kind=Pod name=kubeshark-hub note="Failed to pull image \"kubeshark/hub:37.0\": rpc error: code = NotFound desc = failed to pull and unpack image \"docker.io/kubeshark/hub:37.0\": failed to resolve reference \"docker.io/kubeshark/hub:37.0\": docker.io/kubeshark/hub:37.0: not found" pod=kubeshark-hub reason=Failed
```

### Describe the solution you'd like to see

Ideal solution is to be able to set container image tag in configuration per component, meaning hub, worker...with defaults to `latest` or change defaults to tag versions of all components per release.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
Starting in V38 we introduced this CLI option: `-t, --docker-tag string         The tag of the Docker images that are going to be pulled. (default "latest")` 
For example, you can run Kubeshark like this: `kubeshark tap -A -docker-tag v0.3.0 ` which will pull docker images with tag: V0.3.0. See tag list [here](https://github.com/kubeshark/hub/tags). This will be useful for version starting from V38 and forward.

If you'd like to use V37 or prior, I suggest to simply download V37 release.

**Comment by alen-z** [comment]
Ow, tag reference is for hub, not for `kubeshark/kubeshark`! Tested, works :) Thank you for quick reply. My tag is set in YAML configuration and referenced with `--configpath`.

Keep up great work.
