### ISSUE TITLE
kubeshark tap ignores --proxy-front-port and --proxy-hub-port

### ISSUE THREAD

**Issue by talkain** [kubeshark/kubeshark#1297]
Given specific values using `--proxy-front-port 8001 --proxy-hub-port 8002`, kubeshark ignores them and uses the default values

**To Reproduce**
1. Run `kubeshark tap -n test --proxy-host 127.0.0.1 --proxy-front-port 8001 --proxy-hub-port 8002`
2. Look at the generated URLs (still port 8898)
4. Generate a new config file `kubeshark config > /tmp/kubeshark-config`
5. Change the ports in the new kubeshark config file
6. Run `kubeshark tap -n test--debug --configpath /tmp/kubeshark-config` and see the values were changed

**Desktop (please complete the following information):**
 - OS: macOS
 - kubeshark 38.1

**Comment by mertyildiran** [comment]
@talkain fixed with https://github.com/kubeshark/kubeshark/commit/1c35a9f143b4e4b67a473786a1d99a8533d9da90

[The release 38.2](https://github.com/kubeshark/kubeshark/releases/tag/38.2) has this patch.
