### ISSUE TITLE
Offline deployment

### ISSUE THREAD

**Issue by xujb977644703** [kubeshark/kubeshark#1298]
version 38.3
How to install offline in the internal network?
when  run:    kubeshark check
imagesPullIncluster.go:49 unable to pull images from docker hub

**Comment by xujb977644703** [comment]
![image](https://user-images.githubusercontent.com/38559608/212604337-22578e6e-ad2b-4ff6-816d-c09c062f07f5.png)

**Comment by alongir** [comment]
Please see if this helps: https://docs.kubeshark.co/en/config#private-docker-registry

**Comment by xujb977644703** [comment]
> Please see if this helps: https://docs.kubeshark.co/en/config#private-docker-registry
![image](https://user-images.githubusercontent.com/38559608/212652597-d9d66c22-46b1-491b-8737-de537c1334f0.png)

**Comment by xujb977644703** [comment]
> Please see if this helps: https://docs.kubeshark.co/en/config#private-docker-registry

![image](https://user-images.githubusercontent.com/38559608/212653475-08e146cc-7e2f-4fa6-8b27-456a42caeecf.png)
