### ISSUE TITLE
[Feature Request:] Fixed position for service map node/graph

### ISSUE THREAD

**Issue by ii64** [kubeshark/kubeshark#1302]
### Contact Details

richiisei@gmail.com

### Is your feature request related to a problem? Please describe.

Service map graph comes with a nice beating and wobbly animation when there's a packet captured by kubeshark worker(s), but at a specific case it made a service node (or cluster if they're connected) actively moving anywhere, attached a video about it in [Additional Context].

### Describe the solution you'd like to see

Fixed position for service map node/graph

### Provide additional context

https://user-images.githubusercontent.com/26342994/212879184-e524247f-8c69-4b1d-a5b4-ebcc1af9812d.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@ii64 the graph is bound to the state in left-pane (streamed items) and it's updated for every 500 milliseconds. But the video shows a more frequent tick rate. I'm not sure what causes that. Cloud you please stop the stream (click the pause button) and see if the graph settles?

**Comment by ii64** [comment]
@mertyildiran Yes, the graph settles after stream is stopped.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/26342994/212990029-c5d2b218-cb3b-4ac6-b510-bd188e7a6241.mp4
</details>

**Comment by mertyildiran** [comment]
@ii64 wobbling problem in Service Map is fixed with https://github.com/kubeshark/front/commit/b063cf7eea3cb077bdb6a6356ad766c810912508
