### ISSUE TITLE
"Pod was not ready in time" even though it was

### ISSUE THREAD

**Issue by ccoors** [kubeshark/kubeshark#1304]
**Describe the bug**
Kubeshark claims "Pod was not ready in time" for the `kubeshark-hub` pod after two minutes, but pod was ready and running.

**Provide more information**
Running on AWS EKS (`1.22.15-eks`).

**To Reproduce**
1. Run `kubeshark tap`
2. Watch the resources being created in `kubeshark` namespace (in my case with k9s)
3. The pods become ready, but kubeshark doesn't seem to recognize that and runs into a timeout after  two minutes.

**Expected behavior**
I would have expected kubeshark to recognize the running pod and continue with the tap setup.

**Logs**
[kubeshark_logs_2023_01_23__16_05_29.zip](https://github.com/kubeshark/kubeshark/files/10480906/kubeshark_logs_2023_01_23__16_05_29.zip)

**Screenshots**
Starting Kubeshark in left terminal, see resources and pods in right terminal (k9s)

![log_start](https://user-images.githubusercontent.com/8963459/214071506-ccee7edc-f2c7-44a8-854e-819b5845c95b.png)

Timeout after two minutes:

![log_err](https://user-images.githubusercontent.com/8963459/214071604-ca60c3bb-f506-42ac-a782-caf82163495b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Web Browser: N/A

**Comment by mertyildiran** [comment]
@ccoors please try [the release 38.4](https://github.com/kubeshark/kubeshark/releases/tag/38.4), we changed the approach so now it shouldn't remove the Kubeshark resources in case of proxy/port-forward connection failures or image pull delays.

**Comment by ccoors** [comment]
Unfortunately that does not work:

![frontend](https://user-images.githubusercontent.com/8963459/215416394-f3a0ef68-44c0-4b02-9b05-90a96609193f.png)

The hub-Pod now produces new error messages:

```
2023-01-30T07:37:47Z DBG pkg/worker/targets.go:33 > Doing set targeted pods request: url=http://127.0.0.1:8897/pods/set-targeted
2023-01-30T07:37:47Z ERR pkg/worker/targets.go:36 > Set targeted pods request: error="Post \"http://127.0.0.1:8897/pods/set-targeted\": dial tcp 127.0.0.1:8897: connect: connection refused" url=http://127.0.0.1:8897/pods/set-targeted
2023-01-30T07:37:47Z ERR main.go:61 > error="Post \"http://127.0.0.1:8897/pods/set-targeted\": dial tcp 127.0.0.1:8897: connect: connection refused"
```

[kubeshark_logs_2023_01_30__08_37_50.zip](https://github.com/kubeshark/kubeshark/files/10533521/kubeshark_logs_2023_01_30__08_37_50.zip)

**Comment by mertyildiran** [comment]
@ccoors seems like workers are really not there. Since Hub is unable to see them through K8s API and the logs related to Kubeshark workers are missing.

- What's the log in the CLI?
- How many nodes do you have in the cluster?
- Do you have a CNI plugin? If so, which one? with version?
 
Workers are actually a DaemonSet, so no nodes equals no Kubeshark workers. Maybe you can try to deploy a dummy DaemonSet to see what happens?

**Comment by ccoors** [comment]
Interesting. I just tried again with 38.5 and now it just works:tm: 

![daemonset](https://user-images.githubusercontent.com/8963459/216549037-b666cc9c-9491-47fa-9434-06cf5c179e8c.png)

I don't really understand why, though. The changes from 38.4 to 38.5 should not make a difference. Never mind, thank you for your help!
