### ISSUE TITLE
Your project saved me hours of debugging

### ISSUE THREAD

**Issue by ThisIsQasim** [kubeshark/kubeshark#1310]
### Is your feature request related to a problem? Please describe.

Thank you for this project!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
@ThisIsQasim thanks!! Can you share more information so we'd know how Kubeshark provides value (so we can double down where it matters) ?

**Comment by ThisIsQasim** [comment]
Yes sure. I was migrating a java application to a new cluster and was seeing some unexpected 401s in the logs. Couldn't figure out which user it was and where it was coming from since I had copied over the credentials as is. So I fired up `kubeshark` and noticed that the errors were coming from the internal port which was now expecting auth but wasn't supposed to.
