### ISSUE TITLE
[Feature Request:]How to export a complete yaml file

### ISSUE THREAD

**Issue by clcc2019** [kubeshark/kubeshark#1313]
### Contact Details

dsong.cc@gmail.com

### Is your feature request related to a problem? Please describe.

Support exporting a yaml file set

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@clcc2019 I guess you're looking for the Kubernetes manifests and in that case the list of commands would be:

```
kubectl get pod kubeshark-front -n kubeshark -o yaml
kubectl get pod kubeshark-hub -n kubeshark -o yaml
kubectl get pod kubeshark-worker-daemon-set-hj4jz -n kubeshark -o yaml
```

`kubeshark-worker-daemon-set-*` has a random suffix. You can learn its name through: `kubectl get pod -n kubeshark`

**Comment by acarvalhopt** [comment]
Just a note i exported some more than that..

kubectl get pod kubeshark-front -n kubeshark -o yaml > kubeshark-front.yaml
kubectl get pod kubeshark-hub -n kubeshark -o yaml > kubeshark-hub.yaml
kubectl get pod kubeshark-worker-daemon-set -n kubeshark -o yaml > kubeshark-worker-daemon-set.yaml
kubectl get service/kubeshark-hub -n kubeshark -o yaml > kubeshark-hub-svc.yaml
kubectl get service/kubeshark-front -n kubeshark -o yaml  > kubeshark-front-svc.yaml
kubectl get endpoints kubeshark-front -n kubeshark -o yaml > kubeshark-front-endpoint.yaml
kubectl get endpoints kubeshark-front -n kubeshark -o yaml > kubeshark-hub-endpoint.yaml
kubectl get endpoints kubeshark-hub -n kubeshark -o yaml > kubeshark-hub-endpoint.yaml
kubectl get sa kubeshark-service-account -n kubeshark -o yaml > kubeshark-sa.yaml
kubectl get namespace kubeshark -o yaml > kubeshark-namespace.yaml

**Comment by mertyildiran** [comment]
The Kubernetes manifests are now being dumped into source tree and can be found in [here](https://github.com/kubeshark/kubeshark/tree/master/manifests).

The `kubeshark manifests --dump` command is added to automatically generate the Kubernetes manifests. So, there is no need for running a collection of `kubectl get` commands anymore.

Please try [the release `40.0`](https://github.com/kubeshark/kubeshark/releases/tag/40.0)

**Comment by acarvalhopt** [comment]
Thank you mertyildiran.

I'm using a ingress too.

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeshark-ingress
  namespace: kubeshark
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com # Replace with your desired hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubeshark-frontend
            port:
              name: http
`
