### ISSUE TITLE
[Feature Request:] ability to add labels to all resources generated by kubeshark 

### ISSUE THREAD

**Issue by mbristol580** [kubeshark/kubeshark#1316]
### Contact Details

mbristol@guidewire.com

### Is your feature request related to a problem? Please describe.

Currently we cannot use this  tool in our kubernetes clusters because we have web hooks in place now that require certain labels to be added or else the resource being created will be denied / not created.

### Describe the solution you'd like to see

the ability from the config file to add labels for each resources that kubeshark will create, and/or just one new location that will add labels to all.

config.yaml
 
//default labels for all resources to be added to anything additional added by kubeshark
```
labels: 
       [list of labels]
```

//more fine grain labels ability to add labels only to certain resources generated 
```
resources:
   worker: 
       labels:
              [list of labels]
   hub:
         labels:
              [list of labels]

  etc ....
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@mbristol580 implemented with:
- https://github.com/kubeshark/kubeshark/commit/d9ec538aff2d4813ab6950bdb923ddd4a6d07e53
- https://github.com/kubeshark/kubeshark/commit/b7f0dd7f3cbf54789f4bd6997a4387ea6e91b13f

You can use `resourceLabels` field in the `config.yaml` to set the required labels.

**Comment by mbristol580** [comment]
have confirmed labels are working ! and can add what i need ! Thanks
