### ISSUE TITLE
flag proxy.host not found when running from remote

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1320]
**Describe the bug**
Not sure whether it's a bug or not. When I'm running KS on my minikube like this:
```bash 
ks  tap -A --proxy-host 0.0.0.0
```
Where the IP is <front-end-ip>,
I'm able to access the front-end from a remote machine, using:
```bash 
http://<front-end-ip>:8899/
```
However, when I run
```bash
ks console --proxy-host <front-end-ip>
```
I get:
```
2023-03-23T09:35:13-07:00 WRN config.go:157 > error="flag \"console.proxy.host\" not found"
```
This is the same for 
```bash
ks proxy
``` 
command.
The help section indicates these should work.

**Provide more information**
Minikube, single node, both machines run MacOS

**To Reproduce**
1. Run ks  tap -A --proxy-host 0.0.0.0 on one machine
2. Run ks console --proxy-host <front-end-ip> on the remote machine
3. See the error in the console

**Expected behavior**
I expect that these commands will connect to the remote server.

**Comment by mertyildiran** [comment]
@alongir fixed with https://github.com/kubeshark/kubeshark/commit/261df8261f9d270871191721a0d9d6a42a08fa8a please try [version 39.5](https://github.com/kubeshark/kubeshark/releases/tag/39.5)
