### ISSUE TITLE
config selfnamespace directive isn't working as expected and kubeshark tap -n "namespace" documentation is confusing

### ISSUE THREAD

**Issue by mbristol580** [kubeshark/kubeshark#1323]
**Describe the bug**
According to the documentation if you supply -n "namespace" to the tap command all resources should be created under that namespace. 

https://docs.kubeshark.co/en/scope

By default, Kubeshark is deployed into the default namespace under the name kubeshark

Another connected issue is if i change the config.yaml from the .kubeshark directory and change the 
`selfnamespace: kubeshark` to something else,
 the resources get created under that namespace but then the connection between the resources start throwing errors.

`2023-03-24T10:28:30-05:00 WRN hub.go:110 > Failed sending the storage limit to Hub. Retrying... error="got response with status code: 500, body: {\"msg\":\"Post \\\"http://127.0.0.1:8897/pcaps/set-storage-limit\\\": dial tcp 127.0.0.1:8897: connect: connection refused\"}"`

**Provide more information**
Running on EKS with aws.

**To Reproduce**
1. Run `kubeshark tap -n "choose whatever name you want `
2. Review all pods / resources that were created either by looking at k8 or k9s. 
3. Notice that the namespace is created with the default configured "kubeshark"

Second issue
1. update config.yaml and change selfnamespace: whatever name you want
2. Run `kubeshark tap -n "choose whatever name you want `
3. Review all pods / resources that were created either by looking at k8 or k9s. 
4. you will notice that it is created under now whatever namespace you picked however you should see errors under the hub resources 
`2023-03-24T10:28:30-05:00 WRN hub.go:110 > Failed sending the storage limit to Hub. Retrying... error="got response with status code: 500, body: {\"msg\":\"Post \\\"http://127.0.0.1:8897/pcaps/set-storage-limit\\\": dial tcp 127.0.0.1:8897: connect: connection refused\"}"`

**Expected behavior**
For the first case i expect that -n command on kubeshark tap to associated all resources under that name as the documentation states.

For the second case, all i did was change the default namespace and it should not have had a connection issue 

**Logs**

**Screenshots**

![Screenshot 2023-03-24 at 2 02 43 PM](https://user-images.githubusercontent.com/127255927/227617153-1ab6d44c-9e7d-4b1f-b97c-0fef7aace9b3.png)
![Screenshot 2023-03-24 at 2 06 01 PM](https://user-images.githubusercontent.com/127255927/227617551-e398788b-407e-4c50-8057-b438b534a262.png)

Second case 

current config.file
![Screenshot 2023-03-24 at 2 13 05 PM](https://user-images.githubusercontent.com/127255927/227618671-670e9f82-e0a4-4353-a77f-1ee71b1c7e1b.png)
![Screenshot 2023-03-24 at 2 14 47 PM](https://user-images.githubusercontent.com/127255927/227619029-43513377-39b1-4131-851d-4efa5bb9d620.png)

![Screenshot 2023-03-24 at 2 15 33 PM](https://user-images.githubusercontent.com/127255927/227619313-5c666ad4-3caf-49a6-8387-d8b4e6d151c8.png)

**Desktop (please complete the following information):**
 - OS: macOs
 - Web Browser: google chrome

**Additional context**

**Comment by alongir** [comment]
@mbristol580 
`kubeshark -n <namespace>` taps a certain namespace and does not deploy Kubeshark's resources in that namespace.
Resources will be deployed in the namespace indicated by `selfnamespace` where the default is `kubeshark`. I agree that docs section that relates to the tap scope is confusing. I also confirm the the `selfnamespace` directive isn't working as expected. I assume this is the bug report.
Your two issues are clear. Let me get back to you on that.
Can I assume Kubeshark runs well when using the default `kubeshark` namespace?

**Comment by mertyildiran** [comment]
@mbristol580 fixed with https://github.com/kubeshark/kubeshark/commit/7f6f710b3f63d8967abf59559dc85e8901980a3f and https://github.com/kubeshark/worker/commit/b1189c0c72d12cb116cc652738a9d4a5177babad please try [version 39.5](https://github.com/kubeshark/kubeshark/releases/tag/39.5)
