### ISSUE TITLE
[Feature Request] Add nodeSelector support to kubeshark pods

### ISSUE THREAD

**Issue by coreywagehoft** [kubeshark/kubeshark#1327]
### Is your feature request related to a problem? Please describe.

When creating Kubeshark pods on a cluster through the CLI it will schedule to any node in a cluster.  We run hybrid Kubernetes clusters with Linux and Windows nodes.  Since Kubeshark does not support Windows it should not schedule its pods to windows nodes.

### Describe the solution you'd like to see

The ability to either select node OS or the full Kubernetes nodeSelector spec to be used in `kubeshark tap`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@coreywagehoft thanks for the feature request. We will implement this in the next release and I'll update you.

**Comment by mertyildiran** [comment]
@coreywagehoft `nodeSelectorTerms` option is added to `config.yaml` with:
- https://github.com/kubeshark/kubeshark/commit/d1b17d4534a00e136f45a64fba081f708d67b27c
- https://github.com/kubeshark/kubeshark/commit/02990912b74b957564740fe635109b85dac72a4a

You can either set it in the `config.yaml` and use [the release `40.0`](https://github.com/kubeshark/kubeshark/releases/tag/40.0)

or set it in the `values.yaml`:

https://github.com/kubeshark/kubeshark/blob/26c9f42eba44f56af0dccba763cf93def7ff3dff/helm-chart/values.yaml#L45

and use the Helm chart to install Kubeshark.
