### ISSUE TITLE
[Feature Request:] Support for gp2 EBS volumes for kubeshark daemonset in EKS

### ISSUE THREAD

**Issue by balajisa09** [kubeshark/kubeshark#1341]
### Contact Details

sabalaji09@gmail.com

### Is your feature request related to a problem? Please describe.

Currently, the kubeShark helm chart is written in a way that it needs a EFS volume to be shared by all the daemonset pods. Is it possible to use a hostpath /app/data as a volume mount for the pods or have a stateful set (replicas = no of nodes) with pod anti affinity to attach indivual pv for each pod ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gangstead** [comment]
Could the daemonset workers just not use a PVC and push all their data to the hub without persisting anything?

**Comment by alongir** [comment]
@balajisa09 and @gangstead - Thanks for your feedback! The introduction of a persistent volume did introduce a few unforeseen (by us) challenges.  We will address the persistency and type of volume soon.

**Comment by mertyildiran** [comment]
@balajisa09 I recommend removing these lines:

https://github.com/kubeshark/kubeshark/blob/2563cc19221fb5007411613694777c0e80b717c1/helm-chart/templates/09-worker-daemon-set.yaml#L70-L71

https://github.com/kubeshark/kubeshark/blob/2563cc19221fb5007411613694777c0e80b717c1/helm-chart/templates/09-worker-daemon-set.yaml#L88-L90

and then running `helm install kubeshark .` under [`kubeshark/helm-chart`](https://github.com/kubeshark/kubeshark/tree/2563cc19221fb5007411613694777c0e80b717c1/helm-chart) directory as a dirty solution for now.

We don't have such a Helm template that disables the `PersistentVolumeClaim` altogether.

**Comment by mertyildiran** [comment]
> Could the daemonset workers just not use a PVC and push all their data to the hub without persisting anything?

@gangstead it was like that in the earlier versions of Kubeshark. But we moved into such an architecture that the captured traffic is stored and processed per-node. The benefits are:

- Don't double or even triple the network traffic of the cluster by constantly moving traffic captures to a central location from each node
- A per-node packet capture, dissection and filtering solution that distributes the load across the cluster.
- On-demand dissection and filtering of the traffic to minimize the overall disk and CPU usage.

**Comment by mertyildiran** [comment]
We have made the PVC optional (disabled by default) as of [the release 40.2](https://github.com/kubeshark/kubeshark/releases/tag/40.2)

The `persistentstorage` field in both `config.yaml` and `values.yaml` (Helm) can be set to `true` to enable the PVC.

The flag `--persistentstorage` of `tap` command enables the PVC.
