### ISSUE TITLE
[Feature Request:] Apply for listing in ArtifactHub

### ISSUE THREAD

**Issue by GeiserX** [kubeshark/kubeshark#1347]
### Is your feature request related to a problem? Please describe.

[ArtifactHub](https://artifacthub.io/) contains a list of all installable Helm charts supercharged with functionalities, which makes DevOps work easier.

I have searched for Kubeshark project there but it's not listed. You will need to apply for `Official status request` and request your Helm repository to be included [here](https://github.com/artifacthub/hub/issues/new/choose)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
@GeiserX - thanks for the detailed instructions. 
On it ..
🙏🙏🙏
