### ISSUE TITLE
Helm chart - Follow best practices for namespace assignment

### ISSUE THREAD

**Issue by GeiserX** [kubeshark/kubeshark#1349]
**Describe the bug**
The [best practice](https://github.com/helm/helm/issues/5465) for applying objects to namespaces in Helm is to use `.Release.Namespace`. 
Additionally, we could leave `.Values.tap.namespaces` for selecting the namespaces to track with Kubeshark.

**Expected behavior**
Select deployment namespace through the `-n` argument in helm, defaulting to `kubeshark`, or `namespace:` option in Helmfile.

PS. I'm creating a Pull Request now

**Comment by mertyildiran** [comment]
Please see: https://github.com/kubeshark/kubeshark/pull/1350#discussion_r1184321331

**Comment by mertyildiran** [comment]
Fixed with https://github.com/kubeshark/kubeshark/commit/b9f9e860b6065f276ddacab9aca848ebf0bd6fd9
