### ISSUE TITLE
Worker port changing doesn't work

### ISSUE THREAD

**Issue by greggameplayer** [kubeshark/kubeshark#1351]
**Describe the bug**
I've put 25565 as worker port like so : 
![image](https://user-images.githubusercontent.com/33609333/235803519-1af36ebb-8e18-4fc2-9908-8058c85ac95c.png)

but when executing the command ``kubeshark tap``.
It deploys with the default port 8897 which says in the pods that are already been used.

**Provide more information**
3 Nodes, K3S, 2 Masters, 1 Worker, all connected under tailscale network

**To Reproduce**
1. Modify the config like above
2. Run ``kubeshark tap``
**Expected behavior**
The workers still use 8897

**Comment by alongir** [comment]
I tried as well. Also tried installing via a helm chart and changing the value of the worker port. Port stays 8897.

**Comment by mertyildiran** [comment]
@greggameplayer fixed with https://github.com/kubeshark/kubeshark/commit/f68fed0de8ebd74be3f041cce96651cdb95e980e please try [the release 40.2](https://github.com/kubeshark/kubeshark/releases/tag/40.2).
