### ISSUE TITLE
Is it possible to run kubshark without PVC

### ISSUE THREAD

**Issue by rjshrjndrn** [kubeshark/kubeshark#1352]
Thank you for this amazing tool.

But after uprgading to the latest v40.0, the daemonset need PVC. Is there any way to run this without a storage requirement? especially in local debugging single node clusters

**Comment by alongir** [comment]
In V40.0 we've introduced the volume persistency feature to ensure no data is lost. From the reactions, we understand the current solution doesn't support all K8s distributions. Solution is in the works. We'll report asap, once a solution is available. As our workload is relatively high at this point, this is a matter of ~ 1-2 weeks.

Thanks for reporting the problem!

In the meanwhile, please follow: https://github.com/kubeshark/kubeshark/issues/1337

**Comment by mertyildiran** [comment]
@rjshrjndrn we have made the PVC optional (disabled by default) as of [the release 40.2](https://github.com/kubeshark/kubeshark/releases/tag/40.2)

The `persistentstorage` field in both `config.yaml` and `values.yaml` (Helm) can be set to `true` to enable the PVC.

The flag `--persistentstorage` of `tap` command enables the PVC.
