### ISSUE TITLE
Kubeshark doesn't work on Talos

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1353]
### Is your feature request related to a problem? Please describe.

Steps to reproduce:
1. Install Talos
2. Install Kubeshark
3. UI looks like this:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1990761/236935210-e6530c21-72f8-45e0-9c5c-2d45a1d5fa41.png">

Worker doesn't run on node. 
The following log message appears in the HUB:
```bash
2023-05-08T21:02:48Z ERR pkg/worker/targets.go:36 > Set targeted pods request: error="Post \"http://127.0.0.1:8897/pods/set-targeted\": dial tcp 127.0.0.1:8897: connect: connection refused" url=http:// │
│
```
Can't try changing port due to this: https://github.com/kubeshark/kubeshark/issues/1351

Logs attached:
[kubeshark_logs.zip](https://github.com/kubeshark/kubeshark/files/11425184/kubeshark_logs.zip)

### Original Thread

https://www.reddit.com/r/kubernetes/comments/12yr93v/cant_make_kubeshark_work/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AAm-kun** [comment]
Yes, I'm having the same problem like we discussed.

**Comment by ahmadzana** [comment]
Check the firewall rules it might be blocking the request

**Comment by alongir** [comment]
I'm by no mean an expert in Talos, however this caused Kubeshark to work on Talos. Needless to say, this is probably not a long term solution:
``` bash
kubeshark clean 
kubectl create namespace kubeshark
kubectl label ns kubeshark pod-security.kubernetes.io/enforce=privileged
kubeshark tap
```

**Comment by alongir** [comment]
I'm by no means an expert in Talos. It seams that Talos Pod Security has something to do with Kubeshark not running out of the box on Talos. 
Here's a temporary solution that works:
```bash
kubeshark clean
 kubectl create namespace kubeshark  
kubectl label ns kubeshark pod-security.kubernetes.io/enforce=privileged
kubeshark tap
```
