### ISSUE TITLE
[Feature Request:] Allow for cli to customize k8s annotations

### ISSUE THREAD

**Issue by Gby56** [kubeshark/kubeshark#1354]
### Is your feature request related to a problem? Please describe.

If the cluster is fairly well-protected, you might find out that you can't automount some service account tokens, which are used by Kubeshark apparently.
https://kyverno.io/policies/other/restrict_automount_sa_token/restrict_automount_sa_token/

Bypassing that issue could maybe be achieved if you can specify some annotation, to say the daemonset/pod is authorized

### Describe the solution you'd like to see

A way to inject custom annotations when using the cli, instead of the helm chart install.
That way you can still use it as a simple cli tool (by the way, it seems that cleanup doesn't happen on CTRL+C/exit of the cli sometimes ?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gby56** [comment]
oh it looks like it's exactly the same use-case as https://github.com/kubeshark/kubeshark/issues/1284 but they used OPA :)

**Comment by alongir** [comment]
@Gby56 - `^C` no longer cleans up. You need to run `kubeshark clean` before **or** after running `tap`. We know that this is not optimal and it is likely to be improved soon. `kubeshark tap` continues to run in the background after `^C` allowing you to use `kubeshark proxy` to re-establish dashboard connection. This was an interim solution to overcome the fragility of the `proxy/port-forward` tunnel.

**Comment by alongir** [comment]
@Gby56 Original feature request is done. You can use the Configuration fields to set annotations. Similar can be achived by using only the CLI:
<img width="413" alt="image" src="https://github.com/kubeshark/kubeshark/assets/1990761/61a10428-3a9a-41b5-9268-febec178f960">
LMK if you need further help here.
