### ISSUE TITLE
BUG: In V40.3, changing Hub/Worker/Front port(s) causes Kubeshark not to work

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1359]
**Describe the bug**

Kubeshark Version: 40.3

When ports are changed in the configuration file, Kubeshark doesn't function and a message related to Nginx appears.
Ports change is required to work in environments such as K3s.

For example, this configuration:
```js
  proxy:
    worker:
      srvport: 30001
    hub:
      port: 30002
      srvport: 30002
    front:
      port: 30003
      srvport: 30003
    host: 127.0.0.1
```
Results in this message:
<img width="877" alt="image" src="https://github.com/kubeshark/kubeshark/assets/1990761/13984379-6d26-49d4-bb90-108b0954d847">

**Provide more information**
Minikube, K3s

**To Reproduce**
1. Download 40.3
2. change the port configuration as above
3. Run Kubeshark

See original message: https://kubeshark.slack.com/archives/C04BZMZ5DFA/p1684930493646229

**Comment by mertyildiran** [comment]
Fixed in [version 40.5](https://github.com/kubeshark/kubeshark/releases/tag/40.5).
