### ISSUE TITLE
Bug: -d option doesn't work

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1361]
**Describe the bug**
run `kubeshark tap -d` and it says that the option doesn't work any more.
<img width="1061" alt="image" src="https://github.com/kubeshark/kubeshark/assets/1990761/e606643f-ca36-4e4f-9446-08e12ea0fb51">
Running V40.5 on MACOS.

**Comment by mertyildiran** [comment]
Fixed with https://github.com/kubeshark/kubeshark/commit/bf3285cb8b4e1b6b1e19e964fca51c57a5b13902
