### ISSUE TITLE
Unable to use Kubeshark on local docker-desktop cluster

### ISSUE THREAD

**Issue by MT91-dev** [kubeshark/kubeshark#1368]
**Describe the bug**
I have installed the Kubeshark CLI onto my machine which is a Mac running OS Ventura version 13.4. After successful installation, when running kubeshark tap, I get an error pertaining to an issue with the helm templates. Currently, there are no apps running on my local cluster in docker-desktop except for the default pods that spin up for k8s when its initially booted up. 

**Provide more information**
Currently only trying to test this through docker-desktop and using the local Kubernetes cluster that is spun up with it.

**To Reproduce**
1. Install docker desktop and ensure Kubernetes is enabled.
2. Have kubernetes-cli is installed for running kubectl commands.
3. Switch the current cluster/context to the cluster for docker-desktop.
4. Instal kubeshark, either with the curl installation or with homebrew.
5. After successful installation, run command `kubeshark tap`
6. Error displayed is `error="template: kubeshark/templates/04-hub-pod.yaml:20:25: executing \"kubeshark/templates/04-hub-pod.yaml\" at <len .Values.tap.namespaces>: error calling len: len of nil pointer"`
7. Alternatively, can also run command `kubeshark tap -n default`
8. In this case, error displayed is `error="template: kubeshark/templates/04-hub-pod.yaml:28:25: executing \"kubeshark/templates/04-hub-pod.yaml\" at <len .Values.tap.ingress.auth.approvedDomains>: error calling len: len of nil pointer"`

**Expected behavior**
Based on the documentation for kubeshark, by running `kubeshark tap` it should be able to detect the pods in all the namespaces and spin up the pods for front, hub and daemon. It should also provide me with the localhost url that I can visit and view the pods that are being monitored. Although with nothing deployed, there shouldn't be any API calls happening live for me to see, but I was expecting to see the pods displayed that are being monitored. I cannot even get to that step as the `kubeshark tap` command errors out and does not progress.

**Logs**
Upload logs:
When trying to obtain the logs with the `kubeshark tap --set dump-logs=true` command, it throws an error displaying `error="flag \"dump-logs\" not found"`. Screenshots for all the cases are provided below

**Screenshots**
Kubeshark installation and version information:
<img width="2134" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/fc2452f2-22ab-476e-80c4-8a12a7e8f505">

Error with trying to dump logs:
<img width="1878" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/f289a792-e5be-40e6-94c1-6020971d072d">

Running `kubeshark tap`
<img width="2339" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/a72de6e5-f935-47ec-88d8-c6deb2233913">

Running `kubeshark tap -n default`
<img width="2352" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/a3b49df0-bec1-4743-b776-a23b47d907a9">

Running `kubeshark tap --proxy-host 0.0.0.0`
<img width="2343" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/d39bfd72-ae69-4eff-9bc2-d03c7a737217">

Running `kubectl get nodes -A`
<img width="651" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/04b3ed79-ce41-40e2-a4aa-4194ea31a23a">

Running `kubectl get namespaces -A`
<img width="758" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/5547efa6-71f6-4513-967f-3739389a738c">

Running `kubectl get pods -A -o wide`
<img width="2162" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/113b0d7d-1709-4788-a2f0-b673cb9b0cb1">

Running `kubectl config current-context`
<img width="711" alt="image" src="https://github.com/kubeshark/kubeshark/assets/103468517/00a21bc7-7f5c-4b14-96b5-724045d982e1">

**Desktop (please complete the following information):**
 - OS: Mac Ventura version 13.4
 - Web Browser: Google Chrome

**Additional context**
At this time, there is no additional context that I can provide asides from the screenshots and text above explaining the issues. However, if additional information pertaining to debugging is needed, I can certainly help to provide that.

**Comment by mertyildiran** [comment]
@MT91-dev fixed with https://github.com/kubeshark/kubeshark/commit/bada6dae68a03627ea8ed193313be229ede56daa please try [version 41.1](https://github.com/kubeshark/kubeshark/releases/tag/41.1) Simply upgrade it by running:

```shell
sh <(curl -Ls https://kubeshark.co/install)
```

**Comment by mertyildiran** [comment]
> Hello @mertyildiran thank you for the response, upgrading to 41.1 was able to resolve the issues with the previous errors I was facing. However, now with 41.1, when I am running `kubeshark tap`, it throws the following error:
> 
> ![image](https://user-images.githubusercontent.com/103468517/247598354-3b7f8296-3ba4-4a76-9faf-c8c3cb5db23f.png)
> 
> It ends up hanging after the last command and I have to ctrl + c to exit out of it. Also I do see that you have closed the issue so I am not sure if I should be responding here or creating a new issue for what I am facing now?

The port numbers `8898` and `8899` are already in use on your computer. You can check it using `sudo lsof -i -P -n | grep 8899` command. First stop the process that uses those ports. If it's a `kubeshark tap` or `kubeshark proxy` process hanging for some reason, kill such processes as well. Alternatively, set different port numbers using `--proxy-hub-port` and `--proxy-front-port` flags as it's suggested in the error log.

The error log is related to a failure in establishing proxy because of the ports that are already in use. Therefore the error is unrelated to this issue and I don't think it needs a new issue as well.
