### ISSUE TITLE
storagelimit value is ignored when using the CLI

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1369]
CLI version 41.1, is ignoring the storagelimit variable both when provided at the command line and in the config file. The console logs do show that a new storagelimit value was received: `Kubeshark will store the traffic up to a limit (per node). Oldest TCP/UDP streams will be removed once the limit is reached. limit=300Mi`. Yet, the storage file reaches 200MB and restarts.

**Comment by mertyildiran** [comment]
Modifications on `storagelimit` requires `persistentstorage` to be enabled. Like:

```yaml
  persistentstorage: false
  storagelimit: 300Mi
```

The messages printed to `stdout` are fixed with https://github.com/kubeshark/kubeshark/commit/cc980dbaf8952c560db7e0ad611cf6fa90e5a8e6
