### ISSUE TITLE
[Feature Request:] Allow adding annotations to Ingress & allow selecting another IngressClass

### ISSUE THREAD

**Issue by GeiserX** [kubeshark/kubeshark#1371]
### Contact Details

sergio19932@gmail.com

### Is your feature request related to a problem? Please describe.

Currently, the ingressClass value in the Ingress definition is [fixed](https://github.com/kubeshark/kubeshark/blob/master/helm-chart/templates/11-ingress.yaml#L17) to the IngressClass created by the chart. I will never use it, as I have my own sctrictly-defined ingress classes, so I would like to have a parameter for it.

Additionally, I would like to add custom annotations to the ingress. Currently, for certmanager to start creating a new cert, I have to add an annotation to the ingress like `kubernetes.io/tls-acme: "true"`

### Describe the solution you'd like to see

Allow templating through Helm of both points

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
In the next release

**Comment by mertyildiran** [comment]
Implemented with:
 - https://github.com/kubeshark/kubeshark/commit/16f1e116c01c75f1c002e78d7b76fb132101274a
 - https://github.com/kubeshark/kubeshark/commit/1404c68a22b5dd1cefa30afdac5be2a7426083d6
 - https://github.com/kubeshark/kubeshark/commit/f32a7d97eca794b35543fb78215ce326a6f04af4
 - https://github.com/kubeshark/kubeshark/commit/19443501da4e23c5581602e89441f41387ca2898
