### ISSUE TITLE
Upgrade the existing config file without loosing existing values

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1372]
### Contact Details

alongir@gmail.com

### Is your feature request related to a problem? Please describe.

Currently, when a new release is out, sometimes the configuration structure changes, requiring ti run `kubeshark config -r` that overrides the previous configuration file, loosing all values inside.

### Describe the solution you'd like to see

while `kubeshark config` writes the new structure of a configuration file, `kubeshark config -r` will attempt to merge an existing configuration file to its new format.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
Implemented with https://github.com/kubeshark/kubeshark/commit/5f9084e497b89d1795d3c453376735e2f1182c3a 

```bash
kubeshark config > kubeshark.yaml
```
