### ISSUE TITLE
View an S3 archive (immutable snapshot) in docker mode

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1374]
> At this time, the scope of these features is limited to AWS S3. In the future, we may broaden the scope to other datastores.

An **Immutable Snapshot** is a result of copying an S3 bucket at a certain time to an immutable archive. The archive includes a folder per node, where each folder includes multiple pairs of PCAP and name-resolution JSON files. The archive is a result of using the PCAP helper and uploading the result to an S3 bucket.

**Required**: When pointed to the S3 immutable instance folder, use Kubeshark in docker mode to explore the entire archive.

**Comment by mertyildiran** [comment]
Implemented with https://github.com/kubeshark/kubeshark/commit/242a276c5f07587bfa0ea08fba47d886834dbe5a and https://github.com/kubeshark/kubeshark/commit/261e850a59481e86c41da529c55631d83e7ddd5d
