### ISSUE TITLE
Hardcoded front container port causes SSL not to function

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1375]
Hi everyone, I am having issues with our AWS EKS setup where we terminate SSL on the external ALB and the connection from ALB --> nginx ingress controller --> service is unencrypted. It seems like there is some kind of redirect happening on the Kubeshark level that expects the service endpoint to be accessible on https while the ingress or service objects only provide http ports. I am seeing tons of errors like this on the client (Chrome):
https://shark.internal.domain.name:80/api/pcaps/total-size?refresh-token= net::ERR_SSL_PROTOCOL_ERROR
Obviously, the service port 80 can't handle the https protocol, but I don't know how to turn off the secure access.

Original link: https://discord.com/channels/1042559155224973352/1042561200732512377/1122895915674521642

**Comment by alongir** [comment]
Part of the next release

**Comment by mertyildiran** [comment]
Fixed with:
- https://github.com/kubeshark/front/commit/d2b3c9516a24e990513bd885788ba1b7e4e4a522
- https://github.com/kubeshark/kubeshark/commit/a4761e32625271b0d772dbba13710cb5590448f6
