### ISSUE TITLE
console command results in: error="websocket: bad handshake"

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1379]
**Describe the bug**
1. When running CLI V41.3; and 
2. with the `console` command; and
3. License, `tap.release.namespace` and Ingress are set appropriately; results in:
```shell
 error="websocket: bad handshake"
```

**Provide more information**
Running on EKS with two nodes

**To Reproduce**
1. Deploy Kubeshark using the following Helm command:
```shell
helm install kubeshark kubeshark/kubeshark -n kubeshark --create-namespace \
--set license=<license> \
--set tap.ingress.enabled=true \
--set tap.ingress.host=<url> \
--set "tap.ingress.auth.approveddomains={gmail.com}" \
--set tap.release.namespace=kubeshark \
--set tap.resources.worker.limits.memory=2Gi 
```
2. Run the CLI like this:
```shell
kubeshark console --set license=<license> --set tap.release.namespace=kubeshark
```
3. Watch the results:
<img width="855" alt="image" src="https://github.com/kubeshark/kubeshark/assets/1990761/3dc169e3-800a-4d2e-96d5-577cbd5306e7">

**Comment by mertyildiran** [comment]
Fixed with https://github.com/kubeshark/kubeshark/commit/cfa12ea45eeddef637714bc85049ef29262f4da2
