### ISSUE TITLE
CLI scripts command isn't reading the license from the configuration file

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1380]
**Describe the bug**
When I'm running Kubeshark via Helm, Ingress and a license, and I'd like to use the CLI command `scripts` to upload scripts to the Hub, I expect the CLI to read the license from the configuration file if one is set, similar to reading the scripts source.

**Provide more information**
 EKS

**To Reproduce**
1. Run Kubeshark using Helm with Ingress and provide a license
2. Make sure there is a config file present in `~/kubeshark/config.yaml` and that the license and scripts source are set.
3. Use the CLI: `kubeshark scripts`

**Expected behavior**
I expect that the scripts will be uploaded to the Hub, but instead I get:
<img width="921" alt="image" src="https://github.com/kubeshark/kubeshark/assets/1990761/8981ec0b-92bc-49c6-8dae-860f0a59b67a">

Only when I use --set license=<license> at the command line, scripts are uploaded to the Hub.

**Comment by mertyildiran** [comment]
Couldn't reproduce this issue. It might be the case that the license is not really set in the `config.yaml` or it's incorrect.

Added `license` command with https://github.com/kubeshark/kubeshark/commit/b4e85736346371a66803981680194a295e18e661

Print the license loaded into CLI runtime with: `make && ./bin/kubeshark__` then compare that string to the value of `LICENSE` environment variable in `kubectl describe pod kubeshark-hub` The license strings must be identical to make the authentication work in the `scripts` command.

**Comment by alongir** [comment]
Apparently when I compile `master` locally, it works well. The problem still exists in 41.3.
