### ISSUE TITLE
tap.nodeselectorterms doesn't work when using the CLI

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1389]
## Description
When I set the following in `~/.kubeshark/config.yaml`, it doesn't work:
```shell
tap:
  nodeselectorterms:
  - matchExpressions:
      - key: kubeshark-active
        operator: In
        values:
          - 'true'
```
When I set the following in a Helm command it does:
```shell
--set-json 'tap.nodeselectorterms=[{"matchExpressions": [ {"key":"kubeshark-active", "operator": "In", "values": ["true" ] } ] }]'
```

## Steps to reproduce:
1. Set the configuration file as described above
2. Run Kubeshark CLI V41.3 and Master (e.g. git pull; make)
3. Check the Workers manifest and see:
```shell
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - {}
```
4. Run the Helm command,V 41.5 check the same manifest and see:
```shell
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeshark-active
                    operator: In
                    values:
                      - 'true'
```

**Comment by mertyildiran** [comment]
As of CLI version `50.1` this issue is not present. Probably fixed with https://github.com/kubeshark/kubeshark/commit/a8df589076f3bd4957a979ee3cf5a6b478c8f7df in the past.
