### ISSUE TITLE
[Feature Request:] Support closing auth email & license, through ingress bash auth

### ISSUE THREAD

**Issue by clcc2019** [kubeshark/kubeshark#1405]
### Contact Details

dsong.cc@gmail.com

### Is your feature request related to a problem? Please describe.

We need to temporarily capture packets for debugging, the auth process is too complicated, and we cannot auth via email

### Describe the solution you'd like to see

Support closing auth email & license, through ingress bash auth

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
@clcc2019 we plan to simplify this process (related to Ingress) significantly very soon.

**Comment by alongir** [comment]
This will get resolved during next release by disassociating Ingress from Authentication.

**Comment by alongir** [comment]
You can now use Ingress without Authentication. Just set `tap.auth.enabled=false`
