### ISSUE TITLE
Packet with no data

### ISSUE THREAD

**Issue by vilayilarun** [kubeshark/kubeshark#1421]
### Contact Details

Vilayilarun@gmail.com

### Is your feature request related to a problem? Please describe.

Look like the kubeshark is not monitoring empty packets. 

### Describe the solution you'd like to see

It would be best if you can include of monitoring empty packets 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
@vilayilarun Kubeshak displays traffic from the application layer protocol in the front-end. Empty TCP/UDP packets does not contribute to any application layer protocol. We don't display raw packets. What do you expect to see? What is the use case of seeing empty packets? For example; detection of Denial-of-Service (DoS) attacks?

**Comment by vilayilarun** [comment]
Absolutely, it's important to investigate the root cause of timeouts and slowness between applications. This is particularly relevant when analysing HTTP 408, 499 errors to identify the underlying issues.
