### ISSUE TITLE
[Feature Request:] Hold traffic inspection when

### ISSUE THREAD

**Issue by ep4sh** [kubeshark/kubeshark#1438]
### Contact Details

ep4sh2k@gmail.com

### Is your feature request related to a problem? Please describe.

Good day!
As far as I understood, traffic inspection is going to continue even I close the UI, so kubeshark continues to consume the resources. It would be great if somehow we're able to hold packet inspection in k8s and start it by demand.

thank you so much for your time,
P.

### Describe the solution you'd like to see

Start/stop button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mertyildiran** [comment]
Coincidentally we just made this change and it will be like that in the next release.

**Comment by ep4sh** [comment]
Woo! Looks like The Universe responds to me :)
Thanks a lot, @mertyildiran, appreciate it!
