### ISSUE TITLE
config -r isn't merging existing configuration with new structure

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1444]
**Version**: V51.0.0

**Problem**: `ks config -r` isn't merging previous config with new config file

**Reproduction Steps**:
1. Have an existing config file, with some values
2. Run `ks config -r`
3. Check the new config file and see it is using default values

**Expected Behavior**:
To see a new configuration file with values from previous config file as much as possible

**Comment by mertyildiran** [comment]
`kubeshark config > ~/.kubeshark/config.yaml` supports this use case.
