### ISSUE TITLE
Enabling scripts break workers

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1445]
**Describe the bug**
Enabling scripting cause Worker to crash repeatedly 

**Provide more information**
V51.0.0 (and canary above)

**To Reproduce**
1. Add a script (the default / empty one)
2. Save it
3. Wait for a few minutes
4. See that Workers crash repeatedly

**Comment by mertyildiran** [comment]
Fixed with https://github.com/kubeshark/worker/commit/67521c201ef540140fa99f902ff8d30666b969f8

**Comment by alongir** [comment]
Thats was fast! :satisfied:
