### ISSUE TITLE
[Feature Request:]Support tracking mysql db traffic

### ISSUE THREAD

**Issue by clcc2019** [kubeshark/kubeshark#1461]
### Contact Details

dsong.cc@gmail.com

### Is your feature request related to a problem? Please describe.

I build a mysql service in the cluster. My service accesses mysql, but kubeshark cannot capture the mysql traffic. My pod accesses services outside the cluster and cannot capture the traffic.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alongir** [comment]
https://github.com/kubeshark/kubeshark/issues/1373
