### ISSUE TITLE
PF_RING phase II

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1464]
## Context

PF_RING is an OS extension. When exist, Kubeshark can leverage and perform more efficiently.
When loading PF_RING by Kubeshark Worker:
1. Increase complexity of Kubeshark
2. Requires elevated security capabilities (SYS_MODULE)
3. As the pre-built image is built, downloaded  and loaded with elevated permissions by Kubeshark, it imposes a security risk that reduces the confidence and introduces adoption friction.

## Required

- Make building the kernel module files a separate and transparent process that is vetted and operated by the user 
- Ensure kernel module is uploaded before the Worker runs

### PF_RING files docker image & creation
- Provide means (e.g. a goalang CLI)
- Identify kubectx and run against the cluster
- Create a custom container image
- Image includes all relevant PF_RING.ko files for the certain K8s cluster (consider multiple node architectures)
- Consider that this process can run multiple times and should provide a way to version control
- This image should be hosted in the local registry 
- Introduce a capability to manually perform the entire process end to end with no further dependencies (e.g. create, ssh to node and load modules across all cluster nodes)

### PF-RING Loader image

- Consider whether we need two images or can do with only one
- Image should run before the Worker as part of the DeamonSet
- If necessary load the node-architecture appropriate PF_RING module 
- Should have elevated security capability
- Integrate to Kubeshark Helm template

**Comment by corest** [comment]
This task was implemented with a different approach.
There is `auto` load mode, when kubeshark worker loads pf-ring.
And there is `kmm` mode, when https://github.com/kubernetes-sigs/kernel-module-management does module loading
 All the details are documented here https://github.com/kubeshark/kubeshark/blob/master/helm-chart/PF_RING.md
