### ISSUE TITLE
Namespace Kubeshark installation Vs Cluster Kubeshark installation

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1481]
**Current**:
At this point we can install Kubeshark in a single namespace (E.g. default, kubeshark) and can not install in a different namespace in the same time, due to a shared resource.

**Requested**:
Enable installing Kubeshark in different namespaces without any shared resources.
Assume ports are different and are changed via the values.yaml

**desired Outcome**:
I can install Kubeshark using something like `ks tap -s <ns1>` and do it in the same time using `ks tap -s <ns2>` - I'll need diffrent config file so the ports won't be shared.

**Comment by corest** [comment]
Done
