### ISSUE TITLE
Improve support for homebrew

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1488]
- Install Kubeshark using Homebrew
- If possible, enable doing so without adding a tap prior (think best-in-class homebrew app)
- Fix the [version issue ](https://github.com/kubeshark/kubeshark/issues/1345)
- In the[ install script,](https://github.com/kubeshark/kubeshark/blob/master/install.sh) identify a situation when you install via Homebrew and a version of kubeshark was already installed using the install script and state that any prior version will be deleted.
- Do the same in the homebrew version.

**Comment by corest** [comment]
1. Fix version issue
2. Fix install script
3. Send PR to brew/core with kubeshark to be available without explicit tap

**Comment by corest** [comment]
1. Done

Regarding install script, I have questions
- If kubeshark installed with homebrew and now we run install script, should it:
1.  only inform user about kubeshark existing installation
2.  inform AND delete existing installation before proceeding (like do actual `brew uninstalll`)

- If kubeshark installed with install script and now we run brew install, should it:
1.  only inform user about kubeshark existing installation
2.  inform AND delete existing installation before proceeding (removing binary with rm)

@alongir

**Comment by alongir** [comment]
Inform AND delete. In both cases.

**Comment by corest** [comment]
@alongir in installation script it is possible to do "brew uninstall kubeshark" -> PR here https://github.com/kubeshark/kubeshark/pull/1503

But it is not possible vice versa.
If brew runs `rm` for file created by installation script - it fails due to that file created with sudo.
And sudo is not allowed to be used in brew formulae.

Should we proceed then only with removing kubeshark for case when we install with script?
Because I'd rather keep it informative in both cases, then removing in one and failing in another

**Comment by corest** [comment]
2. done

3. in progress
- PR on review https://github.com/Homebrew/homebrew-core/pull/164578
- We need to automate version updates after PR is merged https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#create-your-pull-request-from-a-new-branch

**Comment by SMillerDev** [comment]
You probably want these for automated bumps instead of reinventing the wheel:
https://github.com/marketplace/actions/bump-homebrew-formula or https://github.com/marketplace/actions/homebrew-bump-formula

**Comment by corest** [comment]
@SMillerDev there was no plan to invent the wheel) It was just a note to not forget about it. Thank you for the links!

**Comment by corest** [comment]
Ok, that took some time, but it is done now
