### ISSUE TITLE
Specific PCAP TTL for Errors

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1494]
**Context**:
- When an error is reported in the dashboard, the only artifact that matters is the PCAP. At this point, when the TTL is 10s, I can only either record the traffic or increase PCAP TTL for everything - both methods aren't convenient.

**Requested:**
- Add a special Error PCAP TTL that will covern the TTL of reported errors (e.g. TCP, ICMP and other errors)

**Comment by mertyildiran** [comment]
https://github.com/kubeshark/kubeshark/commit/92dab2e2f768d2437c79e35bae761a65cc4b097f

https://github.com/kubeshark/worker/commit/ce1b491c1399ef6307e1033b85f1fc4ed05305bd
