### ISSUE TITLE
no push access for the kubeshark fork

### ISSUE THREAD

**Issue by chenrui333** [kubeshark/kubeshark#1521]
👋 right now, there are automated homebrew updates, but there is no push access for the bot account to push the bottle commits change, can you guys update it? Thanks!

relates to:
- https://github.com/Homebrew/homebrew-core/pull/166610
- https://github.com/Homebrew/homebrew-core/pull/166250

cc @alongir

**Comment by alongir** [comment]
thanks @chenrui333! @corest FYI
