### ISSUE TITLE
Remove the deprecated `export` command from the CLI

### ISSUE THREAD

**Issue by fjellvannet** [kubeshark/kubeshark#1556]
**Describe the bug**

The command `kubeshark export` does not work. At first, it says `export.go: 45 > Couldn't connect to Hub. Establishing proxy...`

And then, regularly, `hub.go:269 > Failed exported PCAP download. Retrying... error="got response with status code: 404, body: 404 page not found"`

**Provide more information**

The cluster is a microk8s-cluster with three x86 Ubuntu 24.04 nodes, each with 8 vCPU's and 16 GB RAM. 

The web UI works fine, except that I have not found the button to export a PCAP shown [in this YouTube tutorial](https://www.youtube.com/watch?v=W5NF7eh7uHY) either. 

**To Reproduce**
1. Install the newest Linux x86 CLI as instructed on the [release page](https://github.com/kubeshark/kubeshark/releases/tag/v52.3.68)
2. Make sure the cluster is accessible in .kube/config
3. Run `kubeshark tap --set dump-logs=true` to install kubeshark with the default configuration
4. Run `kubeshark export --set dump-logs=true`

**Expected behavior**

I would expect it to work and a `.tar.gz` file to appear in my `~/.kubeshark´ - directory. One such file appears for each run, but it has a size of 0 bytes and is not valid. The errors also indicate that it probably does not work.

**Logs**
Upload logs:
1. The logs do not appear in `~/.kubeshark` even though I appended `--set dump-logs=true` to all my commands. I therefore used tee to capture all the command outputs. One empty tgz-file and the log files are attached below:

[1720512682.tar.gz](https://github.com/user-attachments/files/16140667/1720512682.tar.gz)
[kubeshark-export-logs.txt](https://github.com/user-attachments/files/16140668/kubeshark-export-logs.txt)
[kubeshark-tap-logs.txt](https://github.com/user-attachments/files/16140669/kubeshark-tap-logs.txt)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 WSL 1.0 and WSL 2.0, also tried directly from the Ubuntu 24.04 worker node with the same result
 - Web Browser: Mozilla Firefox (not really relevant in this case)

**Additional context**

**Comment by alongir** [comment]
@fjellvannet apologies for the confusion. The `export` command is a deprecated command. We need to remove it. As an alternative, I suggest to look at the following:
1. https://docs.kubeshark.co/en/raw_traffic_capture (we will continue to evolve this one - it will become the easiest solution to simply dump pcap traffic somewhere)
2. https://docs.kubeshark.co/en/traffic_recorder
3. https://docs.kubeshark.co/en/long_term_retention

**Comment by fjellvannet** [comment]
Good idea to remove it if it no longer works yes :) 

An thank you for the links - got both methods to retrieve packet captures to work with them. Also good to know they can be inspected directly on the pod with a remote shell into it.
