### ISSUE TITLE
Kubeshark Crashes When Clicking on HTTP Requests for Detailed View

### ISSUE THREAD

**Issue by xvk1t1** [kubeshark/kubeshark#1643]
I'm using Kubeshark to monitor the HTTP requests exchanged by a 5G core running on my Kubernetes cluster. The issue arises when I click on any of the requests to examine them in detail. At this point, Kubeshark becomes buggy and stops functioning. I've attached a screenshot of the console errors that appear when this happens for your reference.

**To Reproduce**
1. Run `kubeshark tap`
2. Click on '<http_request>'
3. See error

**Expected behavior**
See details of the request.

**Logs**
[kubeshark_logs.zip](https://github.com/user-attachments/files/17800603/kubeshark_logs.zip)

**Screenshots**
![image](https://github.com/user-attachments/assets/0192ec53-fa45-4dad-b0f0-fe307292cc1d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Web Browser: Firefox

**Comment by alongir** [comment]
What Kubeshark version?

**Comment by xvk1t1** [comment]
*Update*

I have tried to reproduce the issue using Google Chrome as web browser but I'm obtaining the same results.

**Comment by tiptophelmet** [comment]
Hi @xvk1t1 !

We appreciate your time in reporting this issue!

✅ The issue has been addressed and fixed. Please expect the fix to be included in our next patch release.

**Comment by xvk1t1** [comment]
Hi @tiptophelmet and @alongir !

Thank you both so much for your time and effort in addressing and fixing this issue. I am eagerly looking forward to the release of the patch to see the fix in action. Thanks again!

Best regards.

**Comment by alongir** [comment]
Hi @xvk1t1, can you test this one: https://github.com/kubeshark/kubeshark/releases/tag/v52.3.92

**Comment by xvk1t1** [comment]
Hi, @alongir the issue is solved. Thank you so much!
